name: clean_animation_course
description: Clean approach to an animation course.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  dependency_manager:
    path: libraries/dependency_manager
  auth:
    path: libraries/modules/auth
  ds:
    path: libraries/ds
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  modular_test: ^2.0.0
  triple_test: ^1.0.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/RiveAssets/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
